services:
  dotnet:
    build:
      context: .
      dockerfile: ./.docker/Containerfile
    working_dir: /app
    volumes:
      - ./src:/app:z
      - nuget-cache:/root/.nuget/packages
    stdin_open: true
    tty: true
    entrypoint: []
    command: ["sleep", "infinity"]

volumes:
  nuget-cache:
