emit:
  - "@typespec/json-schema"

options:
  "@typespec/json-schema":
    emitter-output-dir: "{project-root}/tsp-output"
    bundleId: "schema.json"
    file-type: "json"
    int64-strategy: "string"
